---
name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Install EBPF Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get upgrade -yqq
          sudo apt-get install -y jq gcc clang libc6-dev-i386 libbpfcc-dev libbpf-dev 

      - name:  Compile Object file from Source
        run: |
          clang -g -O2 -Wall -Wextra -target bpf -c -o files/objects/tproxy_splicer.o src/tproxy_splicer.c
          clang -O2 -Wall -Wextra -o files/objects/map_update src/map_update.c 
          chmod +x files/scripts/tproxy_splicer_startup.sh
        
      - name: Tar Object File
        run: |
          tar -cvzf tproxy_splicer.tar.gz --strip-components=1 -C files/ objects scripts services
          
      - name: Upload a built artifact for testing
        if: startsWith(github.ref, 'refs/heads/main') == false
        uses: actions/upload-artifact@v3.1.0
        with:
          name: tproxy_splicer
          path: tproxy_splicer.tar.gz